package fluxaorm

import "fmt"

func (g *codeGenerator) createGetterSetterUint64Nullable(schema *entitySchema, fieldName, entityName, getterSuffix, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s%s() *uint64 {", entityName, fieldName, getterSuffix))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullInt64)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\tasUint64 := uint64(vNullable.Int64)")
	g.addLine("\t\t\t\t\treturn &asUint64")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis, _ := strconv.ParseUint(e.originRedisValues[%d], 10, 64)", g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\tuintValue := uint64(e.originDatabaseValues.F%d.Int64)", g.filedIndex))
	g.addLine("\t\treturn &uintValue")
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")
	if getterSuffix == "" {
		g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *uint64) {", entityName, fieldName))
		g.addLine("\tbindValue := sql.NullInt64{}")
		g.addLine("\tif value != nil {")
		g.addLine("\t\tbindValue.Valid = true")
		g.addLine("\t\tbindValue.Int64 = int64(*value)")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("func (e *%s) Set%s(value uint64) {", entityName, fieldName))
		g.addLine("\tbindValue := sql.NullInt64{}")
		g.addLine("\tif value != 0 {")
		g.addLine("\t\tbindValue.Valid = true")
		g.addLine("\t\tbindValue.Int64 = int64(value)")
		g.addLine("\t}")
	}
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		if getterSuffix == "" {
			g.addLine("\t\tif value != nil {")
			g.addLine("\t\t\tasString = strconv.FormatUint(*value, 10)")
			g.addLine("\t\t}")
		} else {
			g.addLine("\t\tif value != 0 {")
			g.addLine("\t\t\tasString = strconv.FormatUint(value, 10)")
			g.addLine("\t\t}")
		}
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine("\tif bindValue.Valid {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, uint64(bindValue.Int64))", g.filedIndex+1))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"\")", g.filedIndex+1))
		g.addLine("\t}")
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterInt64Nullable(schema *entitySchema, fieldName, entityName, getterSuffix, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s%s() *int64 {", entityName, fieldName, getterSuffix))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullInt64)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn &vNullable.Int64")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis, _ := strconv.ParseInt(e.originRedisValues[%d], 10, 64)", g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn &e.originDatabaseValues.F%d.Int64", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *int64) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullInt64{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.Int64 = *value")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		g.addLine("\t\tif value != nil {")
		g.addLine("\t\t\tasString = strconv.FormatInt(*value, 10)")
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine("\tif bindValue.Valid {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, bindValue.Int64)", g.filedIndex+1))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"\")", g.filedIndex+1))
		g.addLine("\t}")
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterStringNullable(schema *entitySchema, fieldName, entityName, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() *string {", entityName, fieldName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullString)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn &vNullable.String")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis := e.originRedisValues[%d]", g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn &e.originDatabaseValues.F%d.String", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value string) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullString{}")
	g.addLine("\tif value != \"\" {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.String = value")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == value", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine(fmt.Sprintf("\te.addToRedisBind(%d, bindValue.String)", g.filedIndex+1))
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterTimeNullable(schema *entitySchema, fieldName, entityName, providerName string, dateOnly bool) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() *time.Time {", entityName, fieldName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullTime)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn &vNullable.Time")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis, _ := strconv.ParseInt(e.originRedisValues[%d], 10, 64)", g.filedIndex))
		g.addLine("\t\t\tt := time.Unix(fromRedis, 0).UTC()")
		g.addLine("\t\t\treturn &t")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn &e.originDatabaseValues.F%d.Time", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *time.Time) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullTime{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.Time = *value")
	if dateOnly {
		g.addLine("\t\tbindValue.Time = bindValue.Time.Truncate(time.Hour * 24)")
	} else {
		g.addLine("\t\tbindValue.Time = bindValue.Time.Truncate(time.Second)")
	}
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		g.addLine("\t\tif bindValue.Valid {")
		g.addLine("\t\t\tasString = strconv.FormatInt(bindValue.Time.Unix(), 10)")
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine("\tif !bindValue.Valid {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"\")", g.filedIndex+1))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, bindValue.Time.Unix())", g.filedIndex+1))
		g.addLine("\t}")
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterBoolNullable(schema *entitySchema, fieldName, entityName, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() *bool {", entityName, fieldName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullBool)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn &vNullable.Bool")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis := e.originRedisValues[%d] == \"1\"", g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn &e.originDatabaseValues.F%d.Bool", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *bool) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullBool{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.Bool = *value")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		g.addLine("\t\tif value != nil {")
		g.addLine("\t\t\tif *value {")
		g.addLine("\t\t\t\tasString = \"1\"")
		g.addLine("\t\t\t} else {")
		g.addLine("\t\t\t\tasString = \"0\"")
		g.addLine("\t\t\t}")
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine("\tif !bindValue.Valid {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"\")", g.filedIndex+1))
		g.addLine("\t} else if bindValue.Bool {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"1\")", g.filedIndex+1))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"0\")", g.filedIndex+1))
		g.addLine("\t}")
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterFloatNullable(schema *entitySchema, fieldName, entityName, providerName string, precision, size int) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() *float64 {", entityName, fieldName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullFloat64)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn &vNullable.Float64")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis, _ := strconv.ParseFloat(e.originRedisValues[%d], 64)", g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn &e.originDatabaseValues.F%d.Float64", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *float64) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullFloat64{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.Float64 = *value")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tfromRedis := sql.NullFloat64{}")
		g.addLine(fmt.Sprintf("\t\tif e.originRedisValues[%d] != \"\" {", g.filedIndex))
		g.addLine("\t\t\tfromRedis.Valid = true")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis.Float64, _ = strconv.ParseFloat(e.originRedisValues[%d], 64)", g.filedIndex))
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = fromRedis.Valid == bindValue.Valid && math.Round(fromRedis.Float64*math.Pow10(%d)) == math.Round(bindValue.Float64*math.Pow10(%d))", precision, precision))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsource := e.originDatabaseValues.F%d", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tsame = source.Valid == bindValue.Valid && math.Round(source.Float64*math.Pow10(%d)) == math.Round(bindValue.Float64*math.Pow10(%d))", precision, precision))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tsource := e.originDatabaseValues.F%d", g.filedIndex))
		g.addLine(fmt.Sprintf("\tif source.Valid == bindValue.Valid && math.Round(source.Float64*math.Pow10(%d)) == math.Round(bindValue.Float64*math.Pow10(%d)) {", precision, precision))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine("\tif !bindValue.Valid {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, \"\")", g.filedIndex+1))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\te.addToRedisBind(%d, strconv.FormatFloat(bindValue.Float64, 'f', %d, %d))", g.filedIndex+1, precision, size))
		g.addLine("\t}")
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterSetNullable(schema *entitySchema, fieldName, entityName, setName, providerName string) {
	g.addImport("sort")
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() []%s {", entityName, fieldName, setName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullString)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\tsliced := strings.Split(v.(string), \",\")")
	g.addLine(fmt.Sprintf("\t\t\t\t\tvalue := make([]%s, len(sliced))", setName))
	g.addLine("\t\t\t\t\tfor k, code := range sliced {")
	g.addLine(fmt.Sprintf("\t\t\t\t\t\tvalue[k] = %s(code)", setName))
	g.addLine("\t\t\t\t\t}")
	g.addLine("\t\t\t\t\treturn value")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tsliced := strings.Split( e.originRedisValues[%d], \",\")", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\t\tvalue := make([]%s, len(sliced))", setName))
		g.addLine("\t\t\tfor k, code := range sliced {")
		g.addLine(fmt.Sprintf("\t\t\t\tvalue[k] = %s(code)", setName))
		g.addLine("\t\t\t}")
		g.addLine("\t\t\treturn value")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\tif e.originDatabaseValues.F%d.String == \"\" {", g.filedIndex))
	g.addLine("\t\t\treturn nil")
	g.addLine("\t\t}")
	g.addLine(fmt.Sprintf("\t\tsliced := strings.Split(e.originDatabaseValues.F%d.String, \",\")", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\tfinalValue := make([]%s, len(sliced))", setName))
	g.addLine("\t\tfor k, code := range sliced {")
	g.addLine(fmt.Sprintf("\t\t\tfinalValue[k] = %s(code)", setName))
	g.addLine("\t\t}")
	g.addLine("\t\treturn finalValue")
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value ...%s) {", entityName, fieldName, setName))
	g.addLine("\tbindValue := sql.NullString{}")
	g.addLine("\tif len(value) > 0 {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tslice := make([]string, len(value))")
	g.addLine("\t\tfor k, v := range value {")
	g.addLine("\t\t\tslice[k] = string(v)")
	g.addLine("\t\t}")
	g.addLine("\t\tsort.Strings(slice)")
	g.addLine("\t\tasString := strings.Join(slice, \",\")")
	g.addLine("\t\tbindValue.String = asString")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == bindValue.String", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine(fmt.Sprintf("\te.addToRedisBind(%d, bindValue.String)", g.filedIndex+1))
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterBytesNullable(schema *entitySchema, fieldName, entityName, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() []uint8 {", entityName, fieldName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullString)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine("\t\t\t\t\treturn []uint8(vNullable.String)")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis := e.originRedisValues[%d]", g.filedIndex))
		g.addLine("\t\t\treturn []uint8(fromRedis)")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\treturn []uint8(e.originDatabaseValues.F%d.String)", g.filedIndex))
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value []uint8) {", entityName, fieldName))
	g.addLine("\tbindValue := sql.NullString{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.String = string(value)")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		g.addLine("\t\tif value != nil {")
		g.addLine("\t\t\tasString = string(value)")
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine(fmt.Sprintf("\te.addToRedisBind(%d, bindValue.String)", g.filedIndex+1))
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}

func (g *codeGenerator) createGetterSetterEnumNullable(schema *entitySchema, fieldName, entityName, enumName, providerName string) {
	g.addLine(fmt.Sprintf("func (e *%s) Get%s() *%s {", entityName, fieldName, enumName))
	g.addLine("\tif !e.new {")
	g.addLine("\t\tif e.databaseBind != nil {")
	g.addLine(fmt.Sprintf("\t\t\tv, hasInDB := e.databaseBind[\"%s\"]", fieldName))
	g.addLine("\t\t\tif hasInDB {")
	g.addLine("\t\t\t\tvNullable := v.(sql.NullString)")
	g.addLine("\t\t\t\tif vNullable.Valid {")
	g.addLine(fmt.Sprintf("\t\t\t\t\tvalue := %s(vNullable.String)", enumName))
	g.addLine("\t\t\t\t\treturn &value")
	g.addLine("\t\t\t\t}")
	g.addLine("\t\t\t\treturn nil")
	g.addLine("\t\t\t}")
	g.addLine("\t\t}")
	if schema.hasRedisCache {
		g.addLine("\t\tif e.originRedisValues != nil {")
		g.addLine(fmt.Sprintf("\t\t\tif e.originRedisValues[%d] == \"\" {", g.filedIndex))
		g.addLine("\t\t\t\treturn nil")
		g.addLine("\t\t\t}")
		g.addLine(fmt.Sprintf("\t\t\tfromRedis := %s(e.originRedisValues[%d])", enumName, g.filedIndex))
		g.addLine("\t\t\treturn &fromRedis")
		g.addLine("\t\t}")
	}
	g.addLine("\t}")
	g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d.Valid {", g.filedIndex))
	g.addLine(fmt.Sprintf("\t\tenumValue := %s(e.originDatabaseValues.F%d.String)", enumName, g.filedIndex))
	g.addLine("\t\treturn &enumValue")
	g.addLine("\t}")
	g.addLine("\treturn nil")
	g.addLine("}")
	g.addLine("")

	g.addLine(fmt.Sprintf("func (e *%s) Set%s(value *%s) {", entityName, fieldName, enumName))
	g.addLine("\tbindValue := sql.NullString{}")
	g.addLine("\tif value != nil {")
	g.addLine("\t\tbindValue.Valid = true")
	g.addLine("\t\tbindValue.String = string(*value)")
	g.addLine("\t}")
	g.addLine("\tif e.new {")
	g.addLine(fmt.Sprintf("\t\te.originDatabaseValues.F%d = bindValue", g.filedIndex))
	g.addLine("\t\treturn")
	g.addLine("\t}")
	if schema.hasRedisCache {
		g.addLine("\tsame:= false")
		g.addLine("\tif e.originRedisValues != nil {")
		g.addLine("\t\tasString := \"\"")
		g.addLine("\t\tif value != nil {")
		g.addLine("\t\t\tasString = string(*value)")
		g.addLine("\t\t}")
		g.addLine(fmt.Sprintf("\t\tsame = e.originRedisValues[%d] == asString", g.filedIndex))
		g.addLine("\t} else {")
		g.addLine(fmt.Sprintf("\t\tsame = e.originDatabaseValues.F%d == bindValue", g.filedIndex))
		g.addLine("\t}")
		g.addLine("\tif same {")
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine(fmt.Sprintf("\t\tdelete(e.redisBind, %d)", g.filedIndex+1))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	} else {
		g.addLine(fmt.Sprintf("\tif e.originDatabaseValues.F%d == bindValue {", g.filedIndex))
		g.addLine(fmt.Sprintf("\t\tdelete(e.databaseBind, \"%s\")", fieldName))
		g.addLine("\t\treturn")
		g.addLine("\t}")
	}
	g.addLine(fmt.Sprintf("\te.addToDatabaseBind(\"%s\", bindValue)", fieldName))
	if schema.hasRedisCache {
		g.addLine(fmt.Sprintf("\te.addToRedisBind(%d, bindValue.String)", g.filedIndex+1))
	}
	g.addLine("}")
	g.addLine("")
	g.filedIndex++
}
