package fluxaorm

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
)

func (g *codeGenerator) generateCodeForEntity(schema *entitySchema) error {
	packageName := filepath.Base(g.dir)
	fileName := path.Join(g.dir, fmt.Sprintf("%s.go", schema.GetTableName()))
	f, err := os.Create(fileName)
	if err != nil {
		return err
	}
	defer func() {
		_ = f.Close()
	}()

	entityName := g.capitalizeFirst(schema.GetTableName())
	entityPrivate := g.lowerFirst(schema.GetTableName())
	names := &entityNames{
		entityName:          entityName,
		entityPrivate:       entityPrivate,
		providerName:        entityName + "Provider",
		providerNamePrivate: entityPrivate + "Provider",
		sqlRowName:          entityPrivate + "SQLRow",
	}

	g.addImport("github.com/latolukasz/fluxaorm/v2")

	g.generateTypedFields(schema, names)
	g.generateRedisSearchFields(schema, names)
	g.generateProviderAndSQLRow(schema, names)
	g.generateGetByID(schema, names)
	g.generateMustGetByID(names)
	g.generateGetByIDs(schema, names)
	g.generateNewMethods(schema, names)
	g.generateSearchOne(schema, names)
	g.generateSearchMany(schema, names)
	g.generateSearchManyWithTotal(schema, names)
	g.generateCount(schema, names)
	if schema.hasRedisSearch {
		g.generateSearchOneInRedis(schema, names)
		g.generateSearchManyInRedis(schema, names)
		g.generateSearchManyInRedisWithTotal(schema, names)
		g.generateReindexRedisSearch(schema, names)
	}
	g.generateEntityStruct(schema, names)

	g.filedIndex = 0
	err = g.generateGettersSetters(names.entityName, names.providerName, schema, schema.fields)
	if err != nil {
		return err
	}

	// CDC publisher/event-alias/snapshot helpers (only when entity has `dirty=...`).
	g.generateCDCStreamForEntity(schema, names)

	g.writeToFile(f, "// Code generated by fluxaorm; DO NOT EDIT.\n\n")
	g.writeToFile(f, fmt.Sprintf("package %s\n", packageName))
	g.writeToFile(f, "\n")
	g.writeImports(f)
	g.writeToFile(f, g.body)
	_ = f.Close()
	return formatFile(fileName)
}
