services:
  mysql:
    image: mysql/mysql-server:8.0
    volumes:
      - orm_volume_mysql:/var/lib/mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: "%"
  redis:
    image: redis:8.6
    ports:
      - ${LOCAL_IP}:${REDIS_PORT}:6379
    volumes:
      - orm_volume_redis:/data
  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports:
      - ${LOCAL_IP}:${CLICKHOUSE_PORT}:9000
      - ${LOCAL_IP}:${CLICKHOUSE_HTTP_PORT}:8123
    volumes:
      - orm_volume_clickhouse:/var/lib/clickhouse
volumes:
  orm_volume_mysql: {}
  orm_volume_redis: {}
  orm_volume_clickhouse: {}
