//go:build cdc_e2e

package test_generate

// NOTE: These tests must NOT call fluxaorm.Generate() — it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.
//
// Build tag `cdc_e2e` keeps this file out of the default build until TestGenerate
// has produced entities/dirty_streams.go and entities/generateEntityDirty.go.
// Run with: `go test -tags=cdc_e2e -run TestCDCSyncPath ./test_generate/...`
//
// Requires live MySQL + Redis + NATS services (see `docker/docker-compose.yml`).

import (
	"context"
	"encoding/json"
	"sync/atomic"
	"testing"
	"time"

	fluxaorm "github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

// TestCDCSyncPath validates the sync flush publish path: insert/update/delete
// on an entity tagged `orm:"dirty=test_stream,test_stream_b"` produces typed
// DirtyEvents on each of the streams it's tagged into.
func TestCDCSyncPath(t *testing.T) {
	registry := fluxaorm.NewRegistry()
	cdcStreams := []fluxaorm.CDCStream{
		entities.StreamTestStream,
		entities.StreamTestStreamB,
	}
	ctx := fluxaorm.PrepareTablesWithCDC(t, registry, cdcStreams, generateEntityDirty{})
	defer ctx.Engine().Nats("nats").Close()

	// Build a consumer for the primary stream.
	consumerA := fluxaorm.NewCDCConsumer(ctx.Engine(), entities.StreamTestStream).
		OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
			return nil
		}).
		Build()
	defer assertConsumerClose(t, consumerA)

	// INSERT
	e, err := entities.GenerateEntityDirtyProvider.New(ctx)
	assert.NoError(t, err)
	e.SetName("cdc-insert")
	e.SetAge(25)
	assert.NoError(t, ctx.Flush())
	entityID := e.GetID()

	insertEvent := pollCDCEvent(t, ctx, entities.StreamTestStream, entityID, fluxaorm.DirtyInsert, 30*time.Second)
	if !assert.NotNil(t, insertEvent, "no INSERT event received on test_stream") {
		t.FailNow()
	}
	assert.Nil(t, insertEvent.Before, "insert.Before should be nil")
	assert.NotNil(t, insertEvent.After, "insert.After should be populated")
	assert.Equal(t, "cdc-insert", (*insertEvent.After)["Name"])

	// Same event must also reach the second stream.
	insertEventB := pollCDCEvent(t, ctx, entities.StreamTestStreamB, entityID, fluxaorm.DirtyInsert, 30*time.Second)
	if !assert.NotNil(t, insertEventB, "no INSERT event received on test_stream_b") {
		t.FailNow()
	}

	// UPDATE
	e.SetName("cdc-updated")
	e.SetAge(30)
	assert.NoError(t, ctx.Flush())

	updateEvent := pollCDCEvent(t, ctx, entities.StreamTestStream, entityID, fluxaorm.DirtyUpdate, 30*time.Second)
	if !assert.NotNil(t, updateEvent, "no UPDATE event received") {
		t.FailNow()
	}
	assert.NotNil(t, updateEvent.Before, "update.Before should be populated")
	assert.NotNil(t, updateEvent.After, "update.After should be populated")
	assert.Equal(t, "cdc-updated", (*updateEvent.After)["Name"])

	// DELETE
	e.Delete()
	assert.NoError(t, ctx.Flush())

	deleteEvent := pollCDCEvent(t, ctx, entities.StreamTestStream, entityID, fluxaorm.DirtyDelete, 30*time.Second)
	if !assert.NotNil(t, deleteEvent, "no DELETE event received") {
		t.FailNow()
	}
	assert.NotNil(t, deleteEvent.Before, "delete.Before should be populated")
	assert.Nil(t, deleteEvent.After, "delete.After should be nil")
}

// pollCDCEvent fetches batches from the stream's durable consumer until it
// finds a DirtyEvent matching the given entity ID and operation, or times out.
// Acks every message it inspects so the test isn't affected by leftover state.
func pollCDCEvent(t *testing.T, ctx fluxaorm.Context, stream fluxaorm.CDCStream, entityID uint64, op fluxaorm.DirtyOp, deadline time.Duration) *entities.GenerateEntityDirtyDirtyEvent {
	t.Helper()
	pool := ctx.Engine().Nats("nats")
	cons, err := pool.Consumer(stream.Durable())
	if err != nil {
		t.Fatalf("get consumer %s: %v", stream.Durable(), err)
	}
	defer cons.Close()

	timeoutAt := time.After(deadline)
	for {
		pollCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		batch := cons.Fetch(ctx.Engine().NewContext(pollCtx), 16, 3*time.Second)
		cancel()
		for _, msg := range batch.Records() {
			if msg.Data == nil {
				_ = msg.Ack()
				continue
			}
			opHeader := msg.Headers.Get(fluxaorm.HeaderDirtyOp)
			if opHeader == "" {
				_ = msg.Ack()
				continue
			}
			ev := &entities.GenerateEntityDirtyDirtyEvent{}
			if err := decodeDirtyEvent(msg.Data, ev); err != nil {
				_ = msg.Ack()
				continue
			}
			if ev.Op != op || ev.ID != entityID {
				_ = msg.Ack()
				continue
			}
			_ = msg.Ack()
			return ev
		}
		select {
		case <-timeoutAt:
			t.Fatalf("timeout waiting for dirty op=%s id=%d on stream %s", op, entityID, stream.Name())
			return nil
		default:
		}
	}
}

// decodeDirtyEvent unmarshals a JSON-encoded *DirtyEvent[map[string]any] into ev.
func decodeDirtyEvent(data []byte, ev *entities.GenerateEntityDirtyDirtyEvent) error {
	return json.Unmarshal(data, ev)
}

// assertConsumerClose is a no-op for now — StreamConsumer doesn't expose Close().
// The lifecycle is owned by the user's loop; tests just stop calling Consume.
func assertConsumerClose(t *testing.T, _ fluxaorm.StreamConsumer) {
	t.Helper()
}

// TestCDCWatchFields validates the WatchFields filter: Update events that
// don't touch a watched column are dropped before the user handler fires;
// Insert and Delete events always pass through.
func TestCDCWatchFields(t *testing.T) {
	registry := fluxaorm.NewRegistry()
	// generateEntityDirty is tagged into both streams; both must be registered
	// even though this test only consumes from `test_stream`.
	cdcStreams := []fluxaorm.CDCStream{entities.StreamTestStream, entities.StreamTestStreamB}
	ctx := fluxaorm.PrepareTablesWithCDC(t, registry, cdcStreams, generateEntityDirty{})
	defer ctx.Engine().Nats("nats").Close()

	var fired atomic.Int32
	consumer := fluxaorm.NewCDCConsumer(ctx.Engine(), entities.StreamTestStream).
		OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
			fired.Add(1)
			return nil
		}, fluxaorm.WatchFields(entities.GenerateEntityDirtyProvider.Fields.Age)).
		Build()

	// drain pumps the consumer until either the expected handler-fired count is
	// reached or the deadline elapses. Returns the observed count.
	drain := func(expected int32, deadline time.Duration) int32 {
		end := time.Now().Add(deadline)
		for time.Now().Before(end) {
			pumpCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			_ = consumer.Consume(pumpCtx, 16, 1*time.Second)
			cancel()
			if fired.Load() >= expected {
				return fired.Load()
			}
		}
		return fired.Load()
	}

	// INSERT — always fires regardless of WatchFields.
	e, err := entities.GenerateEntityDirtyProvider.New(ctx)
	assert.NoError(t, err)
	e.SetName("watchfields-init")
	e.SetAge(20)
	assert.NoError(t, ctx.Flush())
	assert.Equal(t, int32(1), drain(1, 10*time.Second), "Insert must fire even without watched field changes")

	// UPDATE Name only — Age unchanged, handler must be skipped.
	e.SetName("watchfields-name-only")
	assert.NoError(t, ctx.Flush())
	// Give the dispatch path time to receive + filter the message; the counter
	// must not advance.
	_ = drain(2, 3*time.Second)
	assert.Equal(t, int32(1), fired.Load(), "Update touching only unwatched fields must be filtered out")

	// UPDATE Age — watched field changed, handler must fire.
	e.SetAge(30)
	assert.NoError(t, ctx.Flush())
	assert.Equal(t, int32(2), drain(2, 10*time.Second), "Update touching a watched field must fire")

	// DELETE — always fires regardless of WatchFields.
	e.Delete()
	assert.NoError(t, ctx.Flush())
	assert.Equal(t, int32(3), drain(3, 10*time.Second), "Delete must fire even with WatchFields set")
}
