//go:build cdc_e2e

package test_generate

// NOTE: These tests must NOT call fluxaorm.Generate() — it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.
//
// Build tag `cdc_e2e` keeps this file out of the default build until TestGenerate
// has produced entities/consumers.go and entities/generateEntityDirty.go.
// Run with: `go test -tags=cdc_e2e -run TestOneWrite ./test_generate/...`
//
// Requires live MySQL + Redis + NATS services (see `docker/docker-compose.yml`).

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync/atomic"
	"testing"
	"time"

	fluxaorm "github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// consumerCtx registers every entity the fixture consumers declare. A consumer
// may not name an unregistered entity, so the set is all-or-nothing.
func consumerCtx(t *testing.T) fluxaorm.Context {
	t.Helper()

	return fluxaorm.PrepareTablesWithConsumers(t, FixtureRegistry(), FixtureConsumers(),
		generateEntityDirty{}, generateEntityDirtyB{}, generateEntityOutbox{},
		fluxaorm.CDCOutboxEntity{}, fluxaorm.JobRunEntity{})
}

// TestOneWriteIsOneMessageHoweverManyConsumers is the test the whole topology
// change exists for.
//
// generateEntityDirty is declared by two consumers. Under the old
// one-stream-per-consumer model every write was published once per consumer;
// now the subject identifies the entity and both consumers filter it, so the
// flush publishes exactly one message and each durable is owed it once.
//
// The assertion is on the publish, not just on what the stream ended up
// holding: identical copies share a Nats-Msg-Id, so the dedup window would hide
// a return to publish-time fan-out from a stored-message count.
func TestOneWriteIsOneMessageHoweverManyConsumers(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	before := entityStreamMessages(t, ctx)

	published := &natsPublishLog{}
	ctx.RegisterQueryLogger(published, fluxaorm.QueryLoggerOptions{Nats: true})

	e := entities.GenerateEntityDirtyProvider.New(ctx)
	e.SetName("one-write")
	e.SetAge(7)
	require.NoError(t, ctx.Save(e))

	assert.Equal(t, []int{1}, published.batchSizes(),
		"one write must publish one batch of exactly one message, whatever number of consumers declare the entity")

	require.Eventually(t, func() bool {
		return entityStreamMessages(t, ctx) > before
	}, 30*time.Second, 200*time.Millisecond, "no message reached the entity stream")

	assert.Equal(t, before+1, entityStreamMessages(t, ctx), "and the stream stores that one message")

	for _, name := range []fluxaorm.ConsumerName{"test-indexer", "test-notifier"} {
		pending, err := fluxaorm.ConsumerPending(ctx, name)
		require.NoError(t, err)
		assert.Equal(t, uint64(1), pending, "consumer %s must be delivered the one stored message", name)
	}
}

// natsPublishLog records the size of every publish batch on a context.
type natsPublishLog struct{ batches []int }

func (l *natsPublishLog) Handle(_ fluxaorm.Context, log map[string]any) {
	if log["operation"] != "PUBLISH_BATCH" {
		return
	}
	var size int
	if _, err := fmt.Sscanf(log["query"].(string), "messages: %d", &size); err == nil {
		l.batches = append(l.batches, size)
	}
}

func (l *natsPublishLog) batchSizes() []int { return l.batches }

// TestReplayReachesOnlyItsTargetConsumer pins the property the private replay
// subject buys. Replaying one consumer must not re-drive another, or reindexing
// a search index would re-fire whatever side effects the entity's other
// consumers perform.
func TestReplayReachesOnlyItsTargetConsumer(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	e := entities.GenerateEntityDirtyProvider.New(ctx)
	e.SetName("replay-target")
	e.SetAge(3)
	require.NoError(t, ctx.Save(e))

	// Drain the insert from both durables so only the replay is outstanding.
	drainConsumer(t, ctx, entities.ConsumerTestIndexer.Name())
	drainConsumer(t, ctx, entities.ConsumerTestNotifier.Name())

	require.NoError(t, entities.ConsumerTestIndexer.Enqueue(ctx, []fluxaorm.Entity{e}))

	require.Eventually(t, func() bool {
		pending, err := fluxaorm.ConsumerPending(ctx, entities.ConsumerTestIndexer.Name())

		return err == nil && pending == 1
	}, 30*time.Second, 200*time.Millisecond, "replay did not reach its target consumer")

	other, err := fluxaorm.ConsumerPending(ctx, entities.ConsumerTestNotifier.Name())
	require.NoError(t, err)
	assert.Equal(t, uint64(0), other, "replaying one consumer must not re-drive another")
}

// TestMultiSubjectConsumerReceivesAllItsEntities exercises the plural
// FilterSubjects path, which never ran under one-subject-per-consumer.
func TestMultiSubjectConsumerReceivesAllItsEntities(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	var gotA, gotB atomic.Int32
	consumer := fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
		OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
			gotA.Add(1)

			return nil
		}).
		OnGenerateEntityDirtyB(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyBDirtyEvent) error {
			gotB.Add(1)

			return nil
		}).
		Build()

	a := entities.GenerateEntityDirtyProvider.New(ctx)
	a.SetName("multi-a")
	a.SetAge(1)
	b := entities.GenerateEntityDirtyBProvider.New(ctx)
	b.SetLabel("multi-b")
	require.NoError(t, ctx.Save(a, b))

	drainUntil(t, consumer, func() bool { return gotA.Load() >= 1 && gotB.Load() >= 1 }, 30*time.Second)

	assert.Equal(t, int32(1), gotA.Load(), "entity on the first filter subject must arrive")
	assert.Equal(t, int32(1), gotB.Load(), "entity on a later filter subject must arrive too")
}

// TestCDCSyncPath validates the sync flush publish path: insert/update/delete on
// a `cdc`-tagged entity produces typed events on its subject.
func TestCDCSyncPath(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	e := entities.GenerateEntityDirtyProvider.New(ctx)
	e.SetName("cdc-insert")
	e.SetAge(25)
	assert.NoError(t, ctx.Save(e))
	entityID := e.GetID()

	insertEvent := pollEvent(t, ctx, entities.ConsumerTestIndexer.Name(), entityID, fluxaorm.DirtyInsert, 30*time.Second)
	require.NotNil(t, insertEvent, "no INSERT event received")
	assert.Nil(t, insertEvent.Before, "insert.Before should be nil")
	require.NotNil(t, insertEvent.After, "insert.After should be populated")
	assert.Equal(t, "cdc-insert", (*insertEvent.After)["Name"])

	e.SetName("cdc-updated")
	e.SetAge(30)
	assert.NoError(t, ctx.Save(e))

	updateEvent := pollEvent(t, ctx, entities.ConsumerTestIndexer.Name(), entityID, fluxaorm.DirtyUpdate, 30*time.Second)
	require.NotNil(t, updateEvent, "no UPDATE event received")
	assert.NotNil(t, updateEvent.Before, "update.Before should be populated")
	require.NotNil(t, updateEvent.After, "update.After should be populated")
	assert.Equal(t, "cdc-updated", (*updateEvent.After)["Name"])

	assert.NoError(t, ctx.Delete(e))

	deleteEvent := pollEvent(t, ctx, entities.ConsumerTestIndexer.Name(), entityID, fluxaorm.DirtyDelete, 30*time.Second)
	require.NotNil(t, deleteEvent, "no DELETE event received")
	assert.NotNil(t, deleteEvent.Before, "delete.Before should be populated")
	assert.Nil(t, deleteEvent.After, "delete.After should be nil")
}

// TestCDCWatchFields validates the WatchFields filter: Update events that don't
// touch a watched column are dropped before the user handler fires; Insert and
// Delete events always pass through.
func TestCDCWatchFields(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	var fired atomic.Int32
	consumer := fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
		OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
			fired.Add(1)

			return nil
		}, fluxaorm.WatchFields(entities.GenerateEntityDirtyProvider.Fields.Age)).
		Build()

	drain := func(expected int32, deadline time.Duration) int32 {
		end := time.Now().Add(deadline)
		for time.Now().Before(end) {
			pumpCtx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			_ = consumer.Consume(pumpCtx, 16, 1*time.Second)
			cancel()
			if fired.Load() >= expected {
				return fired.Load()
			}
		}

		return fired.Load()
	}

	e := entities.GenerateEntityDirtyProvider.New(ctx)
	e.SetName("watchfields-init")
	e.SetAge(20)
	assert.NoError(t, ctx.Save(e))
	assert.Equal(t, int32(1), drain(1, 10*time.Second), "Insert must fire even without watched field changes")

	e.SetName("watchfields-name-only")
	assert.NoError(t, ctx.Save(e))
	_ = drain(2, 3*time.Second)
	assert.Equal(t, int32(1), fired.Load(), "Update touching only unwatched fields must be filtered out")

	e.SetAge(30)
	assert.NoError(t, ctx.Save(e))
	assert.Equal(t, int32(2), drain(2, 10*time.Second), "Update touching a watched field must fire")

	assert.NoError(t, ctx.Delete(e))
	assert.Equal(t, int32(3), drain(3, 10*time.Second), "Delete must fire even with WatchFields set")
}

// TestCDCBatchDispatch validates that a consumer with batch handlers receives
// all messages for one entity in a single handler call, grouped per entity.
func TestCDCBatchDispatch(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	var aCalls, aEvents, bCalls, bEvents atomic.Int32
	consumer := fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
		OnGenerateEntityDirtyBatch(func(_ fluxaorm.Context, evs []*entities.GenerateEntityDirtyDirtyEvent) error {
			aCalls.Add(1)
			aEvents.Add(int32(len(evs)))

			return nil
		}).
		OnGenerateEntityDirtyBBatch(func(_ fluxaorm.Context, evs []*entities.GenerateEntityDirtyBDirtyEvent) error {
			bCalls.Add(1)
			bEvents.Add(int32(len(evs)))

			return nil
		}).
		Build()

	// One flush, many entities of two types -> one publish batch, and on the
	// consumer side one handler call per entity.
	const perType = 5
	rows := make([]fluxaorm.Entity, 0, perType*2)
	for i := range perType {
		a := entities.GenerateEntityDirtyProvider.New(ctx)
		a.SetName(fmt.Sprintf("batch-a-%d", i))
		a.SetAge(uint64(i))
		b := entities.GenerateEntityDirtyBProvider.New(ctx)
		b.SetLabel(fmt.Sprintf("batch-b-%d", i))
		rows = append(rows, a, b)
	}
	assert.NoError(t, ctx.Save(rows...))

	drainUntil(t, consumer, func() bool {
		return aEvents.Load() >= perType && bEvents.Load() >= perType
	}, 30*time.Second)

	assert.Equal(t, int32(perType), aEvents.Load(), "all GenerateEntityDirty events delivered")
	assert.Equal(t, int32(perType), bEvents.Load(), "all GenerateEntityDirtyB events delivered")
	assert.Equal(t, int32(1), aCalls.Load(), "GenerateEntityDirty events must arrive in one batch call")
	assert.Equal(t, int32(1), bCalls.Load(), "GenerateEntityDirtyB events must arrive in one batch call")
}

// TestCDCBatchDispatchErrorRedelivers validates that a batch handler returning
// an error leaves the whole group unacked, so JetStream redelivers it.
func TestCDCBatchDispatchErrorRedelivers(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	var attempts, delivered atomic.Int32
	consumer := fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
		OnGenerateEntityDirtyBatch(func(_ fluxaorm.Context, evs []*entities.GenerateEntityDirtyDirtyEvent) error {
			if attempts.Add(1) == 1 {
				return errors.New("forced batch failure")
			}
			delivered.Add(int32(len(evs)))

			return nil
		}).
		Build()

	const count = 3
	rows := make([]fluxaorm.Entity, 0, count)
	for i := range count {
		e := entities.GenerateEntityDirtyProvider.New(ctx)
		e.SetName(fmt.Sprintf("batch-retry-%d", i))
		e.SetAge(uint64(i))
		rows = append(rows, e)
	}
	assert.NoError(t, ctx.Save(rows...))

	// AckWait is 30s by default, so redelivery needs a generous window.
	drainUntil(t, consumer, func() bool { return delivered.Load() >= count }, 90*time.Second)

	assert.GreaterOrEqual(t, attempts.Load(), int32(2), "failed batch must be retried")
	assert.Equal(t, int32(count), delivered.Load(), "whole group redelivered after failure")
}

// TestCDCBatchAndSingleHandlerConflictPanics validates the Build() guard: an
// entity may have a per-message handler or a batch handler, never both.
func TestCDCBatchAndSingleHandlerConflictPanics(t *testing.T) {
	ctx := consumerCtx(t)
	defer ctx.Engine().Nats("nats").Close()

	assert.Panics(t, func() {
		fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
			OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
				return nil
			}).
			OnGenerateEntityDirtyBatch(func(_ fluxaorm.Context, _ []*entities.GenerateEntityDirtyDirtyEvent) error {
				return nil
			}).
			Build()
	})

	// Different entities on the same consumer may mix the two styles freely.
	assert.NotPanics(t, func() {
		fluxaorm.NewConsumer(ctx.Engine(), entities.ConsumerTestIndexer).
			OnGenerateEntityDirty(func(_ fluxaorm.Context, _ *entities.GenerateEntityDirtyDirtyEvent) error {
				return nil
			}).
			OnGenerateEntityDirtyBBatch(func(_ fluxaorm.Context, _ []*entities.GenerateEntityDirtyBDirtyEvent) error {
				return nil
			}).
			Build()
	})
}

// entityStreamMessages reads how many messages the shared entity stream holds.
func entityStreamMessages(t *testing.T, ctx fluxaorm.Context) uint64 {
	t.Helper()
	js, err := ctx.Engine().Nats("nats").GetJetStream()
	require.NoError(t, err)
	stream, err := js.Stream(ctx.Context(), fluxaorm.EntityStreamName)
	require.NoError(t, err)
	info, err := stream.Info(ctx.Context())
	require.NoError(t, err)

	return info.State.Msgs
}

// drainConsumer acks everything currently outstanding on one durable.
func drainConsumer(t *testing.T, ctx fluxaorm.Context, name fluxaorm.ConsumerName) {
	t.Helper()
	cons, err := ctx.Engine().Nats("nats").Consumer(string(name))
	require.NoError(t, err)
	defer cons.Close()

	for {
		pollCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		batch := cons.Fetch(ctx.Engine().NewContext(pollCtx), 32, 2*time.Second)
		cancel()
		records := batch.Records()
		for _, msg := range records {
			_ = msg.Ack()
		}
		if len(records) == 0 {
			return
		}
	}
}

// pollEvent fetches from a consumer's durable until it finds an event matching
// the given entity ID and operation, or times out. Acks every message it
// inspects so the test isn't affected by leftover state.
func pollEvent(
	t *testing.T, ctx fluxaorm.Context, name fluxaorm.ConsumerName,
	entityID uint64, op fluxaorm.DirtyOp, deadline time.Duration,
) *entities.GenerateEntityDirtyDirtyEvent {
	t.Helper()
	cons, err := ctx.Engine().Nats("nats").Consumer(string(name))
	if err != nil {
		t.Fatalf("get consumer %s: %v", name, err)
	}
	defer cons.Close()

	timeoutAt := time.After(deadline)
	for {
		pollCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		batch := cons.Fetch(ctx.Engine().NewContext(pollCtx), 16, 3*time.Second)
		cancel()
		for _, msg := range batch.Records() {
			ev := &entities.GenerateEntityDirtyDirtyEvent{}
			if msg.Data == nil || json.Unmarshal(msg.Data, ev) != nil {
				_ = msg.Ack()

				continue
			}
			_ = msg.Ack()
			if ev.Op == op && ev.ID == entityID {
				return ev
			}
		}
		select {
		case <-timeoutAt:
			t.Fatalf("timeout waiting for op=%s id=%d on consumer %s", op, entityID, name)

			return nil
		default:
		}
	}
}

// drainUntil pumps the consumer until done() reports true or the deadline passes.
func drainUntil(t *testing.T, consumer fluxaorm.StreamConsumer, done func() bool, deadline time.Duration) {
	t.Helper()
	end := time.Now().Add(deadline)
	for time.Now().Before(end) {
		if done() {
			return
		}
		pumpCtx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		_ = consumer.Consume(pumpCtx, 32, 1*time.Second)
		cancel()
	}
}
