package test_generate

// NOTE: These tests must NOT call fluxaorm.Generate() - it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.

import (
	"context"
	"testing"
	"time"

	fluxaorm "github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

func TestDebezium(t *testing.T) {
	registry := fluxaorm.NewRegistry()
	subjectName := "fluxa_default.test.generateEntityDebezium"
	consumerName := "debezium_test_consumer"
	registry.RegisterNatsConsumer(
		fluxaorm.NewNatsConsumer(consumerName, "nats").FilterSubjects(subjectName),
	)
	ctx := fluxaorm.PrepareTablesWithDebezium(t, registry, generateEntityDebezium{})
	defer ctx.Engine().Nats("nats").Close()

	// GetNatsAlters and execute any pending alters (create stream + consumer)
	alters, err := fluxaorm.GetNatsAlters(ctx)
	assert.NoError(t, err)
	for _, alter := range alters {
		t.Logf("executing alter: %s", alter.Description)
		assert.NoError(t, alter.Exec(ctx))
	}

	// Wait for Debezium Server to start capturing changes
	time.Sleep(5 * time.Second)

	natsPool := ctx.Engine().Nats("nats")
	cons := natsPool.MustConsumer(consumerName)
	defer cons.Close()

	// INSERT
	e, err := entities.GenerateEntityDebeziumProvider.New(ctx)
	assert.NoError(t, err)
	e.SetName("debezium-test")
	e.SetAge(25)
	assert.NoError(t, ctx.Flush())
	entityID := e.GetID()

	insertEvent := pollDebeziumEvent(t, cons, ctx, entityID, fluxaorm.DebeziumCreate, 60*time.Second)
	if !assert.NotNil(t, insertEvent, "no INSERT event received") {
		t.FailNow()
	}
	assert.Nil(t, insertEvent.Before)
	assert.NotNil(t, insertEvent.After)
	assert.Equal(t, "debezium-test", insertEvent.After["Name"])

	// UPDATE
	e.SetName("debezium-updated")
	e.SetAge(30)
	assert.NoError(t, ctx.Flush())

	updateEvent := pollDebeziumEvent(t, cons, ctx, entityID, fluxaorm.DebeziumUpdate, 60*time.Second)
	if !assert.NotNil(t, updateEvent, "no UPDATE event received") {
		t.FailNow()
	}
	assert.NotNil(t, updateEvent.Before)
	assert.NotNil(t, updateEvent.After)
	assert.Equal(t, "debezium-updated", updateEvent.After["Name"])

	// DELETE
	e.Delete()
	assert.NoError(t, ctx.Flush())

	deleteEvent := pollDebeziumEvent(t, cons, ctx, entityID, fluxaorm.DebeziumDelete, 60*time.Second)
	if !assert.NotNil(t, deleteEvent, "no DELETE event received") {
		t.FailNow()
	}
	assert.NotNil(t, deleteEvent.Before)
	assert.Nil(t, deleteEvent.After)
}

// pollDebeziumEvent polls the NATS consumer until it finds a Debezium event matching
// the given entity ID and operation type, or times out.
func pollDebeziumEvent(t *testing.T, cons fluxaorm.NatsConsumer, ctx fluxaorm.Context, entityID uint64, op fluxaorm.DebeziumOperation, deadline time.Duration) *fluxaorm.DebeziumEvent {
	t.Helper()
	timeoutAt := time.After(deadline)
	for {
		pollCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		batch := cons.Fetch(ctx.Engine().NewContext(pollCtx), 32, 5*time.Second)
		cancel()
		for _, msg := range batch.Records() {
			if msg.Data == nil {
				_ = msg.Ack()
				continue
			}
			ev, err := fluxaorm.ParseDebeziumEvent(msg)
			if err != nil {
				_ = msg.Ack()
				continue
			}
			if ev.Op != op {
				_ = msg.Ack()
				continue
			}
			id, err := fluxaorm.ParseDebeziumKey(msg)
			if err != nil {
				_ = msg.Ack()
				continue
			}
			if id == entityID {
				_ = msg.Ack()
				return ev
			}
			_ = msg.Ack()
		}
		select {
		case <-timeoutAt:
			t.Fatalf("timeout waiting for debezium %s event for entity %d", op, entityID)
			return nil
		default:
		}
	}
}
