package test_generate

// NOTE: These tests must NOT call fluxaorm.Generate() - it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.

import (
	"context"
	"testing"
	"time"

	fluxaorm "github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

func TestDebezium(t *testing.T) {
	registry := fluxaorm.NewRegistry()
	topicName := "fluxa_default.test.generateEntityDebezium"
	groupName := "debezium_test_group"
	registry.RegisterKafkaConsumerGroup(
		fluxaorm.NewKafkaConsumerGroup(groupName, "kafka").Topics(topicName),
	)
	ctx := fluxaorm.PrepareTablesWithDebezium(t, registry, generateEntityDebezium{})
	defer ctx.Engine().Kafka("kafka").Close()

	// GetDebeziumAlters and execute any pending alters (CREATE or UPDATE connector)
	alters, err := fluxaorm.GetDebeziumAlters(ctx)
	assert.NoError(t, err)
	for _, alter := range alters {
		t.Logf("executing alter: %s", alter.Description)
		assert.NoError(t, alter.Exec(ctx))
	}

	// Verify no more alters needed (idempotency)
	time.Sleep(2 * time.Second)
	alters2, err := fluxaorm.GetDebeziumAlters(ctx)
	assert.NoError(t, err)
	assert.Len(t, alters2, 0, "expected no alters after executing all pending alters")

	// Wait for Debezium connector to start capturing changes
	time.Sleep(5 * time.Second)

	// Get consumer group
	kafka := ctx.Engine().Kafka("kafka")
	cg := kafka.MustConsumerGroup(groupName)
	defer cg.Close()

	// INSERT: create entity and flush to MySQL
	e := entities.GenerateEntityDebeziumProvider.New(ctx)
	e.SetName("debezium-test")
	e.SetAge(25)
	assert.NoError(t, ctx.Flush())
	entityID := e.GetID()

	// Poll for INSERT event
	insertEvent := pollDebeziumEvent(t, cg, ctx, entityID, fluxaorm.DebeziumCreate, 60*time.Second)
	if !assert.NotNil(t, insertEvent, "no INSERT event received") {
		t.FailNow()
	}
	assert.Nil(t, insertEvent.Before)
	assert.NotNil(t, insertEvent.After)
	assert.Equal(t, "debezium-test", insertEvent.After["Name"])

	// UPDATE: modify entity
	e.SetName("debezium-updated")
	e.SetAge(30)
	assert.NoError(t, ctx.Flush())

	// Poll for UPDATE event
	updateEvent := pollDebeziumEvent(t, cg, ctx, entityID, fluxaorm.DebeziumUpdate, 60*time.Second)
	if !assert.NotNil(t, updateEvent, "no UPDATE event received") {
		t.FailNow()
	}
	assert.NotNil(t, updateEvent.Before)
	assert.NotNil(t, updateEvent.After)
	assert.Equal(t, "debezium-updated", updateEvent.After["Name"])

	// DELETE: remove entity
	e.Delete()
	assert.NoError(t, ctx.Flush())

	// Poll for DELETE event
	deleteEvent := pollDebeziumEvent(t, cg, ctx, entityID, fluxaorm.DebeziumDelete, 60*time.Second)
	if !assert.NotNil(t, deleteEvent, "no DELETE event received") {
		t.FailNow()
	}
	assert.NotNil(t, deleteEvent.Before)
	assert.Nil(t, deleteEvent.After)
}

// pollDebeziumEvent polls the consumer group until it finds a Debezium event matching
// the given entity ID and operation type, or times out.
func pollDebeziumEvent(t *testing.T, cg fluxaorm.KafkaConsumerGroup, ctx fluxaorm.Context, entityID uint64, op fluxaorm.DebeziumOperation, deadline time.Duration) *fluxaorm.DebeziumEvent {
	t.Helper()
	timeoutAt := time.After(deadline)
	for {
		pollCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		fetches := cg.PollFetches(ctx.Engine().NewContext(pollCtx))
		cancel()
		for _, r := range fetches.Records() {
			// Skip tombstone records (nil value)
			if r.Value == nil {
				continue
			}
			ev, err := fluxaorm.ParseDebeziumEvent(r)
			if err != nil {
				continue
			}
			if ev.Op != op {
				continue
			}
			id, err := fluxaorm.ParseDebeziumKey(r)
			if err != nil {
				continue
			}
			if id == entityID {
				cg.CommitUncommittedOffsets(ctx)
				return ev
			}
		}
		select {
		case <-timeoutAt:
			t.Fatalf("timeout waiting for debezium %s event for entity %d", op, entityID)
			return nil
		default:
		}
	}
}
