package test_generate

import (
	"fmt"
	"testing"
	"time"

	"github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

// NOTE: These tests must NOT call fluxaorm.Generate() - it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.

func TestAfterInsertCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntity *entities.GenerateEntityWithTimestamps
	var callbackCtx fluxaorm.Context
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		callbackCtx = c
		callbackEntity = entity
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("InsertTest")
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackEntity)
	assert.NotNil(t, callbackCtx)
	assert.Equal(t, e.GetID(), callbackEntity.GetID())
	assert.Equal(t, "InsertTest", callbackEntity.GetName())
	assert.False(t, callbackEntity.GetCreatedAt().IsZero())
}

func TestAfterUpdateCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntityID uint64
	var callbackNameDuringCallback string
	var callbackChanges map[string]any
	var updateCalled bool
	entities.GenerateEntityWithTimestampsProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps, changes map[string]any) error {
		updateCalled = true
		callbackEntityID = entity.GetID()
		callbackNameDuringCallback = entity.GetName() // capture NEW value during callback
		callbackChanges = changes
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Original")
	assert.NoError(t, ctx.Flush())

	// Insert callback should not trigger update handler
	assert.False(t, updateCalled)

	// Now update
	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.SetName("Updated")
	assert.NoError(t, ctx.Flush())

	assert.True(t, updateCalled)
	assert.Equal(t, e.GetID(), callbackEntityID)
	// Entity getters returned NEW values during callback execution
	assert.Equal(t, "Updated", callbackNameDuringCallback)
	// Changes map has OLD value
	assert.Equal(t, "Original", callbackChanges["Name"])
}

func TestAfterDeleteCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntity *entities.GenerateEntityWithTimestamps
	entities.GenerateEntityWithTimestampsProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		callbackEntity = entity
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("DeleteTest")
	assert.NoError(t, ctx.Flush())

	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.Delete()
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackEntity)
	assert.Equal(t, e.GetID(), callbackEntity.GetID())
}

func TestAfterDeleteCallbackFakeDelete(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateReferenceEntity{})

	var deleteCallbackEntity *entities.GenerateReferenceEntity
	var updateCalled bool
	entities.GenerateReferenceEntityProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity) error {
		deleteCallbackEntity = entity
		return nil
	})
	entities.GenerateReferenceEntityProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity, changes map[string]any) error {
		updateCalled = true
		return nil
	})

	e := entities.GenerateReferenceEntityProvider.New(ctx)
	e.SetName("FakeDeleteTest")
	assert.NoError(t, ctx.Flush())

	e, _, _ = entities.GenerateReferenceEntityProvider.GetByID(ctx, e.GetID())
	e.Delete() // This is FakeDelete since entity has FakeDelete field
	assert.NoError(t, ctx.Flush())

	// AfterDelete should fire, not AfterUpdate
	assert.NotNil(t, deleteCallbackEntity)
	assert.Equal(t, e.GetID(), deleteCallbackEntity.GetID())
	assert.False(t, updateCalled)
}
func TestAfterFlushCallbacksNoHandler(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	// No handlers registered - flush should work fine
	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("NoHandler")
	assert.NoError(t, ctx.Flush())

	e, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "NoHandler", e.GetName())
}

func TestAfterUpdateExcludesUpdatedAt(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackChanges map[string]any
	entities.GenerateEntityWithTimestampsProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps, changes map[string]any) error {
		callbackChanges = changes
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Original")
	assert.NoError(t, ctx.Flush())

	time.Sleep(time.Second)
	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.SetName("Updated")
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackChanges)
	// UpdatedAt should NOT be in the changes map (it's auto-set)
	_, hasUpdatedAt := callbackChanges["UpdatedAt"]
	assert.False(t, hasUpdatedAt)
	// CreatedAt should NOT be in the changes map either
	_, hasCreatedAt := callbackChanges["CreatedAt"]
	assert.False(t, hasCreatedAt)
	// Name SHOULD be in the changes map
	assert.Equal(t, "Original", callbackChanges["Name"])
}

func TestMultipleEntitiesInSingleFlush(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{}, generateReferenceEntity{})

	var insertedTimestamps []*entities.GenerateEntityWithTimestamps
	var insertedRefs []*entities.GenerateReferenceEntity
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		insertedTimestamps = append(insertedTimestamps, entity)
		return nil
	})
	entities.GenerateReferenceEntityProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity) error {
		insertedRefs = append(insertedRefs, entity)
		return nil
	})

	ts1 := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	ts1.SetName("First")
	ts2 := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	ts2.SetName("Second")
	ref := entities.GenerateReferenceEntityProvider.New(ctx)
	ref.SetName("Ref")

	assert.NoError(t, ctx.Flush())

	assert.Len(t, insertedTimestamps, 2)
	assert.Len(t, insertedRefs, 1)

	names := []string{insertedTimestamps[0].GetName(), insertedTimestamps[1].GetName()}
	assert.Contains(t, names, "First")
	assert.Contains(t, names, "Second")
	assert.Equal(t, "Ref", insertedRefs[0].GetName())
}

func TestAfterCallbackErrorPropagation(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	expectedErr := fmt.Errorf("callback error")
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		return expectedErr
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("ErrorTest")
	err := ctx.Flush()

	// The row is already committed when the handler runs, so the failure is
	// reported as a PostCommitError rather than something the caller may retry.
	assert.ErrorIs(t, err, expectedErr)
	var postCommit *fluxaorm.PostCommitError
	assert.ErrorAs(t, err, &postCommit)

	// Entity was still persisted to DB (callback runs after DB+Redis writes)
	e2, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "ErrorTest", e2.GetName())
}
