package test_generate

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

// NOTE: These tests must NOT call fluxaorm.Generate() - it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.

func TestAfterInsertCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntity *entities.GenerateEntityWithTimestamps
	var callbackCtx fluxaorm.Context
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		callbackCtx = c
		callbackEntity = entity
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("InsertTest")
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackEntity)
	assert.NotNil(t, callbackCtx)
	assert.Equal(t, e.GetID(), callbackEntity.GetID())
	assert.Equal(t, "InsertTest", callbackEntity.GetName())
	assert.False(t, callbackEntity.GetCreatedAt().IsZero())
}

func TestAfterUpdateCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntityID uint64
	var callbackNameDuringCallback string
	var callbackChanges map[string]any
	var updateCalled bool
	entities.GenerateEntityWithTimestampsProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps, changes map[string]any) error {
		updateCalled = true
		callbackEntityID = entity.GetID()
		callbackNameDuringCallback = entity.GetName() // capture NEW value during callback
		callbackChanges = changes
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Original")
	assert.NoError(t, ctx.Flush())

	// Insert callback should not trigger update handler
	assert.False(t, updateCalled)

	// Now update
	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.SetName("Updated")
	assert.NoError(t, ctx.Flush())

	assert.True(t, updateCalled)
	assert.Equal(t, e.GetID(), callbackEntityID)
	// Entity getters returned NEW values during callback execution
	assert.Equal(t, "Updated", callbackNameDuringCallback)
	// Changes map has OLD value
	assert.Equal(t, "Original", callbackChanges["Name"])
}

func TestAfterDeleteCallback(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackEntity *entities.GenerateEntityWithTimestamps
	entities.GenerateEntityWithTimestampsProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		callbackEntity = entity
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("DeleteTest")
	assert.NoError(t, ctx.Flush())

	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.Delete()
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackEntity)
	assert.Equal(t, e.GetID(), callbackEntity.GetID())
}

func TestAfterDeleteCallbackFakeDelete(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateReferenceEntity{})

	var deleteCallbackEntity *entities.GenerateReferenceEntity
	var updateCalled bool
	entities.GenerateReferenceEntityProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity) error {
		deleteCallbackEntity = entity
		return nil
	})
	entities.GenerateReferenceEntityProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity, changes map[string]any) error {
		updateCalled = true
		return nil
	})

	e := entities.GenerateReferenceEntityProvider.New(ctx)
	e.SetName("FakeDeleteTest")
	assert.NoError(t, ctx.Flush())

	e, _, _ = entities.GenerateReferenceEntityProvider.GetByID(ctx, e.GetID())
	e.Delete() // This is FakeDelete since entity has FakeDelete field
	assert.NoError(t, ctx.Flush())

	// AfterDelete should fire, not AfterUpdate
	assert.NotNil(t, deleteCallbackEntity)
	assert.Equal(t, e.GetID(), deleteCallbackEntity.GetID())
	assert.False(t, updateCalled)
}

func TestAfterFlushCallbacksNotFiredForFlushAsync(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	var insertCalled bool
	entities.GenerateEntityWithTimestampsRedisProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestampsRedis) error {
		insertCalled = true
		return nil
	})

	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("AsyncTest")
	assert.NoError(t, ctx.FlushAsync(true))

	assert.False(t, insertCalled)
}

func TestAfterFlushCallbacksNoHandler(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	// No handlers registered - flush should work fine
	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("NoHandler")
	assert.NoError(t, ctx.Flush())

	e, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "NoHandler", e.GetName())
}

func TestAfterUpdateExcludesUpdatedAt(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var callbackChanges map[string]any
	entities.GenerateEntityWithTimestampsProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps, changes map[string]any) error {
		callbackChanges = changes
		return nil
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Original")
	assert.NoError(t, ctx.Flush())

	time.Sleep(time.Second)
	e, _, _ = entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	e.SetName("Updated")
	assert.NoError(t, ctx.Flush())

	assert.NotNil(t, callbackChanges)
	// UpdatedAt should NOT be in the changes map (it's auto-set)
	_, hasUpdatedAt := callbackChanges["UpdatedAt"]
	assert.False(t, hasUpdatedAt)
	// CreatedAt should NOT be in the changes map either
	_, hasCreatedAt := callbackChanges["CreatedAt"]
	assert.False(t, hasCreatedAt)
	// Name SHOULD be in the changes map
	assert.Equal(t, "Original", callbackChanges["Name"])
}

func TestMultipleEntitiesInSingleFlush(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{}, generateReferenceEntity{})

	var insertedTimestamps []*entities.GenerateEntityWithTimestamps
	var insertedRefs []*entities.GenerateReferenceEntity
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		insertedTimestamps = append(insertedTimestamps, entity)
		return nil
	})
	entities.GenerateReferenceEntityProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity) error {
		insertedRefs = append(insertedRefs, entity)
		return nil
	})

	ts1 := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	ts1.SetName("First")
	ts2 := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	ts2.SetName("Second")
	ref := entities.GenerateReferenceEntityProvider.New(ctx)
	ref.SetName("Ref")

	assert.NoError(t, ctx.Flush())

	assert.Len(t, insertedTimestamps, 2)
	assert.Len(t, insertedRefs, 1)

	names := []string{insertedTimestamps[0].GetName(), insertedTimestamps[1].GetName()}
	assert.Contains(t, names, "First")
	assert.Contains(t, names, "Second")
	assert.NotNil(t, insertedRefs[0].GetName())
	assert.Equal(t, "Ref", *insertedRefs[0].GetName())
}

func TestAfterCallbackErrorPropagation(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	expectedErr := fmt.Errorf("callback error")
	entities.GenerateEntityWithTimestampsProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestamps) error {
		return expectedErr
	})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("ErrorTest")
	err := ctx.Flush()

	assert.Equal(t, expectedErr, err)

	// Entity was still persisted to DB (callback runs after DB+Redis writes)
	e2, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "ErrorTest", e2.GetName())
}

func TestAfterInsertCallbackFiredByAsyncConsumer(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	var callbackEntity *entities.GenerateEntityWithTimestampsRedis
	var insertCalled bool
	entities.GenerateEntityWithTimestampsRedisProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestampsRedis) error {
		insertCalled = true
		callbackEntity = entity
		return nil
	})

	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("AsyncInsertTest")
	assert.NoError(t, ctx.FlushAsync(true))

	// Hook should NOT fire during FlushAsync itself
	assert.False(t, insertCalled)

	// Consume the async SQL event
	consumer, err := ctx.GetAsyncSQLConsumer()
	assert.NoError(t, err)
	assert.NoError(t, consumer.Consume(10, time.Millisecond))

	// Hook should have fired in the consumer
	assert.True(t, insertCalled)
	assert.NotNil(t, callbackEntity)
	assert.Equal(t, e.GetID(), callbackEntity.GetID())
	assert.Equal(t, "AsyncInsertTest", callbackEntity.GetName())
	assert.False(t, callbackEntity.GetCreatedAt().IsZero())
}

func TestAfterUpdateCallbackFiredByAsyncConsumer(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	var callbackChanges map[string]any
	var callbackName string
	var updateCalled bool
	entities.GenerateEntityWithTimestampsRedisProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestampsRedis, changes map[string]any) error {
		updateCalled = true
		callbackName = entity.GetName()
		callbackChanges = changes
		return nil
	})

	// Insert entity first (synchronously so it's in DB)
	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("Original")
	assert.NoError(t, ctx.Flush())
	assert.False(t, updateCalled)

	// Update via FlushAsync
	e, _, _ = entities.GenerateEntityWithTimestampsRedisProvider.GetByID(ctx, e.GetID())
	e.SetName("Updated")
	assert.NoError(t, ctx.FlushAsync(true))
	assert.False(t, updateCalled)

	// Consume the async SQL event
	consumer, err := ctx.GetAsyncSQLConsumer()
	assert.NoError(t, err)
	assert.NoError(t, consumer.Consume(10, time.Millisecond))

	assert.True(t, updateCalled)
	// Entity loaded from DB should have the NEW value
	assert.Equal(t, "Updated", callbackName)
	// Changes map should have the OLD value
	assert.Equal(t, "Original", callbackChanges["Name"])
	// Timestamp fields should NOT be in changes
	_, hasUpdatedAt := callbackChanges["UpdatedAt"]
	assert.False(t, hasUpdatedAt)
	_, hasCreatedAt := callbackChanges["CreatedAt"]
	assert.False(t, hasCreatedAt)
}

func TestAfterDeleteCallbackFiredByAsyncConsumer(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	var callbackEntity *entities.GenerateEntityWithTimestampsRedis
	var deleteCalled bool
	entities.GenerateEntityWithTimestampsRedisProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestampsRedis) error {
		deleteCalled = true
		callbackEntity = entity
		return nil
	})

	// Insert entity first (synchronously)
	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("DeleteAsyncTest")
	assert.NoError(t, ctx.Flush())

	// Delete via FlushAsync
	e, _, _ = entities.GenerateEntityWithTimestampsRedisProvider.GetByID(ctx, e.GetID())
	entityID := e.GetID()
	e.Delete()
	assert.NoError(t, ctx.FlushAsync(true))
	assert.False(t, deleteCalled)

	// Consume the async SQL event
	consumer, err := ctx.GetAsyncSQLConsumer()
	assert.NoError(t, err)
	assert.NoError(t, consumer.Consume(10, time.Millisecond))

	assert.True(t, deleteCalled)
	assert.NotNil(t, callbackEntity)
	assert.Equal(t, entityID, callbackEntity.GetID())
}

func TestAfterDeleteCallbackFiredByAsyncConsumerFakeDelete(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateReferenceEntity{})

	var callbackEntity *entities.GenerateReferenceEntity
	var deleteCalled bool
	var updateCalled bool
	entities.GenerateReferenceEntityProvider.OnAfterDelete(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity) error {
		deleteCalled = true
		callbackEntity = entity
		return nil
	})
	entities.GenerateReferenceEntityProvider.OnAfterUpdate(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateReferenceEntity, changes map[string]any) error {
		updateCalled = true
		return nil
	})

	// Insert entity first (synchronously)
	e := entities.GenerateReferenceEntityProvider.New(ctx)
	e.SetName("FakeDeleteAsyncTest")
	assert.NoError(t, ctx.Flush())

	// FakeDelete via FlushAsync
	e, _, _ = entities.GenerateReferenceEntityProvider.GetByID(ctx, e.GetID())
	entityID := e.GetID()
	e.Delete() // FakeDelete since entity has FakeDelete field
	assert.NoError(t, ctx.FlushAsync(true))

	// Consume the async SQL event
	consumer, err := ctx.GetAsyncSQLConsumer()
	assert.NoError(t, err)
	assert.NoError(t, consumer.Consume(10, time.Millisecond))

	// AfterDelete should fire, not AfterUpdate
	assert.True(t, deleteCalled)
	assert.False(t, updateCalled)
	assert.NotNil(t, callbackEntity)
	assert.Equal(t, entityID, callbackEntity.GetID())
}

func TestAfterCallbackErrorInAsyncConsumer(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	expectedErr := fmt.Errorf("async callback error")
	entities.GenerateEntityWithTimestampsRedisProvider.OnAfterInsert(ctx.Engine(), func(c fluxaorm.Context, entity *entities.GenerateEntityWithTimestampsRedis) error {
		return expectedErr
	})

	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("AsyncErrorTest")
	assert.NoError(t, ctx.FlushAsync(true))

	// Consume — hook error should be returned
	consumer, err := ctx.GetAsyncSQLConsumer()
	assert.NoError(t, err)
	err = consumer.Consume(10, time.Millisecond)
	assert.Equal(t, expectedErr, err)

	// Event was ACK'd (SQL committed), stream should be empty
	streamLen, err := ctx.Engine().Redis(fluxaorm.DefaultPoolCode).XLen(ctx, fluxaorm.AsyncSQLStreamName)
	assert.NoError(t, err)
	assert.Equal(t, int64(0), streamLen)

	// Entity should be in MySQL (SQL committed before hook ran)
	freshCtx := ctx.Engine().NewContext(context.Background())
	freshCtx.DisableContextCache()
	_, found, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(freshCtx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
}
