package test_generate

import (
	"errors"
	"strconv"
	"testing"
	"time"

	"github.com/latolukasz/fluxaorm/v2"
	"github.com/latolukasz/fluxaorm/v2/test_generate/entities"
	"github.com/stretchr/testify/assert"
)

// NOTE: These tests must NOT call fluxaorm.Generate() - it clears the entities directory.
// Entities are pre-generated by TestGenerate in generate_test.go.

func TestSaveIsImmediate(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Immediate")
	assert.NoError(t, ctx.Save(e))

	// A second context shares no unit of work and no identity map, so finding
	// the row there proves the write already reached MySQL.
	other := ctx.Clone()
	loaded, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(other, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "Immediate", loaded.GetName())
}

func TestSaveDedupesAndIsIdempotent(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Once")
	assert.NoError(t, ctx.Save(e, e))
	assert.NoError(t, ctx.Save(e))

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx, fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Len(t, all, 1)
}

func TestSaveOfSeveralEntitiesIsAtomic(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityCachedUnique{})

	first := entities.GenerateEntityCachedUniqueProvider.New(ctx)
	first.SetName("A").SetAge(1).SetEmail("clash@example.com")
	second := entities.GenerateEntityCachedUniqueProvider.New(ctx)
	second.SetName("B").SetAge(2).SetEmail("clash@example.com")

	// No explicit Transaction: more than one entity is atomic on its own.
	assert.Error(t, ctx.Save(first, second))

	fresh := ctx.Clone()
	all, err := entities.GenerateEntityCachedUniqueProvider.SearchMany(fresh, fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Empty(t, all)
}

func TestTransactionCommits(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	var id uint64
	assert.NoError(t, ctx.Transaction(func(tx fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(tx)
		e.SetName("Committed")
		id = e.GetID()
		return tx.Save(e)
	}))
	assert.False(t, ctx.InTransaction())

	loaded, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx.Clone(), id)
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "Committed", loaded.GetName())
}

func TestTransactionRollsBackOnError(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	boom := errors.New("boom")
	err := ctx.Transaction(func(tx fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(tx)
		e.SetName("Doomed")
		if sErr := tx.Save(e); sErr != nil {
			return sErr
		}
		return boom
	})
	assert.ErrorIs(t, err, boom)
	assert.False(t, ctx.InTransaction())

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx.Clone(), fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Empty(t, all)
}

func TestTransactionRollsBackOnPanicAndRepanics(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	assert.Panics(t, func() {
		_ = ctx.Transaction(func(tx fluxaorm.Context) error {
			e := entities.GenerateEntityWithTimestampsProvider.New(tx)
			e.SetName("Panicked")
			if sErr := tx.Save(e); sErr != nil {
				return sErr
			}
			panic("mid-write")
		})
	})
	assert.False(t, ctx.InTransaction())

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx.Clone(), fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Empty(t, all)
}

func TestNestedTransactionJoinsTheOuterOne(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	assert.NoError(t, ctx.Transaction(func(outer fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(outer)
		e.SetName("Outer")
		if err := outer.Save(e); err != nil {
			return err
		}
		return outer.Transaction(func(inner fluxaorm.Context) error {
			assert.True(t, inner.InTransaction())
			e2 := entities.GenerateEntityWithTimestampsProvider.New(inner)
			e2.SetName("Inner")
			return inner.Save(e2)
		})
	}))

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx.Clone(), fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Len(t, all, 2)
}

func TestSwallowedNestedFailureStillRollsBackTheOuterTransaction(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	err := ctx.Transaction(func(outer fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(outer)
		e.SetName("Outer")
		if sErr := outer.Save(e); sErr != nil {
			return sErr
		}
		// The caller deliberately ignores the inner failure.
		_ = outer.Transaction(func(fluxaorm.Context) error {
			return errors.New("inner failed")
		})
		return nil
	})
	assert.ErrorIs(t, err, fluxaorm.ErrTxRollbackOnly)

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx.Clone(), fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Empty(t, all)
}

func TestReadYourOwnWriteInsideTransaction(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	assert.NoError(t, ctx.Transaction(func(tx fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(tx)
		e.SetName("Visible")
		if err := tx.Save(e); err != nil {
			return err
		}
		// The read must go through the open transaction, not the pool.
		found, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(tx,
			fluxaorm.NewQuery().Filter(entities.GenerateEntityWithTimestampsProvider.Fields.Name.Is("Visible")))
		assert.NoError(t, err)
		assert.Len(t, found, 1)
		return nil
	}))
}

func TestNoCacheFillInsideTransaction(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	missingID := uint64(123456789)
	err := ctx.Transaction(func(tx fluxaorm.Context) error {
		_, found, gErr := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(tx, missingID)
		assert.NoError(t, gErr)
		assert.False(t, found)
		return errors.New("roll it back")
	})
	assert.Error(t, err)

	// A negative cache entry written inside the transaction would outlive the
	// rollback, so none may be written at all.
	keys, err := ctx.Engine().Redis(fluxaorm.DefaultPoolCode).LRange(ctx, entities.GenerateEntityWithTimestampsRedisProvider.RedisCachePrefix()+strconv.FormatUint(missingID, 10), 0, -1)
	assert.NoError(t, err)
	assert.Empty(t, keys)
}

func TestDeleteOfUnsavedEntityIsRejected(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("NeverSaved")
	assert.ErrorIs(t, ctx.Delete(e), fluxaorm.ErrEntityNotPersisted)
}

func TestDeleteRemovesTheRowFromTheIdentityMap(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Doomed")
	assert.NoError(t, ctx.Save(e))
	assert.NoError(t, ctx.Delete(e))

	_, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.False(t, found)
}

func TestSaveAfterDeleteDoesNotReissueTheDelete(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Gone")
	assert.NoError(t, ctx.Save(e))
	assert.NoError(t, ctx.Delete(e))

	// The `deleted` flag must be cleared, otherwise this re-runs the DELETE and
	// re-publishes the delete event.
	assert.NoError(t, ctx.Save(e))
}

// TestDirtyEntitySurvivesContextCacheEviction covers the failure that reached
// production: unsaved changes were visible only through the identity map, which
// was wiped wholesale on TTL expiry, so later code in the same request silently
// re-read the pre-change row.
func TestDirtyEntitySurvivesContextCacheEviction(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})
	ctx.SetContextCacheTTL(50 * time.Millisecond)

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Before")
	assert.NoError(t, ctx.Save(e))

	loaded, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	loaded.SetName("After")

	time.Sleep(80 * time.Millisecond)

	again, found, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "After", again.GetName())
	assert.Same(t, loaded, again)

	assert.NoError(t, ctx.Save(loaded))
	persisted, _, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx.Clone(), e.GetID())
	assert.NoError(t, err)
	assert.Equal(t, "After", persisted.GetName())
}

func TestCleanEntriesAreStillEvictedFromTheContextCache(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})
	ctx.SetContextCacheTTL(50 * time.Millisecond)

	e := entities.GenerateEntityWithTimestampsProvider.New(ctx)
	e.SetName("Clean")
	assert.NoError(t, ctx.Save(e))

	loaded, _, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)

	time.Sleep(80 * time.Millisecond)

	again, _, err := entities.GenerateEntityWithTimestampsProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.NotSame(t, loaded, again)
}

func TestUpdateInvalidatesTheRowCacheInsteadOfWritingItBack(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})

	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("V1")
	assert.NoError(t, ctx.Save(e))

	// Warm the row cache on a context with its own identity map.
	warm := ctx.Clone()
	_, _, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(warm, e.GetID())
	assert.NoError(t, err)

	writer := ctx.Clone()
	toEdit, _, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(writer, e.GetID())
	assert.NoError(t, err)
	toEdit.SetName("V2")
	assert.NoError(t, writer.Save(toEdit))

	reader := ctx.Clone()
	reloaded, found, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(reader, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "V2", reloaded.GetName())
}

func TestCacheOffGivesTheSameResults(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestampsRedis{})
	ctx.DisableContextCache()

	e := entities.GenerateEntityWithTimestampsRedisProvider.New(ctx)
	e.SetName("NoCache")
	assert.NoError(t, ctx.Save(e))

	loaded, found, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(ctx, e.GetID())
	assert.NoError(t, err)
	assert.True(t, found)
	assert.Equal(t, "NoCache", loaded.GetName())

	loaded.SetName("NoCache2")
	assert.NoError(t, ctx.Save(loaded))

	again, _, err := entities.GenerateEntityWithTimestampsRedisProvider.GetByID(ctx.Clone(), e.GetID())
	assert.NoError(t, err)
	assert.Equal(t, "NoCache2", again.GetName())
}

func TestTransactionWorksWithAMockedDBClient(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithTimestamps{})

	db := ctx.Engine().DB(fluxaorm.DefaultPoolCode)
	execCalls := 0
	db.SetMockDBClient(&fluxaorm.MockDBClient{OriginDB: db.GetDBClient()})

	assert.NoError(t, ctx.Transaction(func(tx fluxaorm.Context) error {
		e := entities.GenerateEntityWithTimestampsProvider.New(tx)
		e.SetName("Mocked")
		execCalls++
		return tx.Save(e)
	}))
	assert.Equal(t, 1, execCalls)

	all, err := entities.GenerateEntityWithTimestampsProvider.SearchMany(ctx.Clone(), fluxaorm.NewQuery())
	assert.NoError(t, err)
	assert.Len(t, all, 1)
}

func TestRolledBackTransactionPublishesNoSearchDocument(t *testing.T) {
	ctx := fluxaorm.PrepareTables(t, fluxaorm.NewRegistry(), generateEntityWithSearch{})

	var rolledBackID uint64
	err := ctx.Transaction(func(tx fluxaorm.Context) error {
		e := entities.GenerateEntityWithSearchProvider.New(tx)
		e.SetName("Rolled").SetAge(1).SetScore(1)
		rolledBackID = e.GetID()
		if sErr := tx.Save(e); sErr != nil {
			return sErr
		}
		return errors.New("roll it back")
	})
	assert.Error(t, err)

	// A later successful write must not carry the discarded search write with it.
	kept := entities.GenerateEntityWithSearchProvider.New(ctx)
	kept.SetName("Kept").SetAge(2).SetScore(2)
	assert.NoError(t, ctx.Save(kept))

	redis := ctx.Engine().Redis(fluxaorm.DefaultPoolCode)
	exists, err := redis.Exists(ctx, entities.GenerateEntityWithSearchProvider.RedisSearchHashPrefix()+strconv.FormatUint(rolledBackID, 10))
	assert.NoError(t, err)
	assert.Zero(t, exists)

	exists, err = redis.Exists(ctx, entities.GenerateEntityWithSearchProvider.RedisSearchHashPrefix()+strconv.FormatUint(kept.GetID(), 10))
	assert.NoError(t, err)
	assert.Equal(t, int64(1), exists)
}
